<?php

namespace ProjetBDD\Thesaurus\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConceptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptRepository extends EntityRepository
{
}