<?php

namespace ProjetBDD\Thesaurus\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermeRepository extends EntityRepository
{
}